[build]
  publish = "public/"

[[plugins]]
package = "netlify-plugin-gatsby-cache"

[[redirects]]
from = "/api/*"
to = "https://oerworldmap.org/:splat"
status = 200
force = true
query = {q = ":q", size = ":size", sort = ":s"}

